### ISSUE TITLE
Segmentation fault in the Fonts tab of Document Properties

### ISSUE THREAD

**Issue by hmenke** [flathub/com.adobe.Reader#4]
To reproduce:

1. Open any PDF file
2. Go to "File" > "Properties..." to open the Document Properties dialog
3. Switch to the Fonts tab and observe the crash

Backtrace:

```c
Thread 1 "acroread" received signal SIGSEGV, Segmentation fault.
0xf65cd86d in g_type_check_instance_is_fundamentally_a () from /app/lib/i386-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0xf65cd86d in g_type_check_instance_is_fundamentally_a () from /app/lib/i386-linux-gnu/libgobject-2.0.so.0
#1  0xf65b3ff0 in g_object_ref () from /app/lib/i386-linux-gnu/libgobject-2.0.so.0
#2  0xeffe7b00 in ?? () from /app/extra/Adobe/Reader9/Reader/intellinux/SPPlugins/ADMPlugin.apl
#3  0xeffca5b9 in ?? () from /app/extra/Adobe/Reader9/Reader/intellinux/SPPlugins/ADMPlugin.apl
#4  0xeffe3a26 in ?? () from /app/extra/Adobe/Reader9/Reader/intellinux/SPPlugins/ADMPlugin.apl
#5  0xeffbb7a3 in ?? () from /app/extra/Adobe/Reader9/Reader/intellinux/SPPlugins/ADMPlugin.apl
#6  0xeffb3590 in ?? () from /app/extra/Adobe/Reader9/Reader/intellinux/SPPlugins/ADMPlugin.apl
#7  0xeff53477 in ?? () from /app/extra/Adobe/Reader9/Reader/intellinux/SPPlugins/ADMPlugin.apl
#8  0x085df48e in ?? ()
#9  0x087c7ef7 in ?? ()
#10 0x08a65978 in ?? ()
#11 0x087b26f4 in ?? ()
#12 0x08a6582a in ?? ()
#13 0x086ba8d9 in ?? ()
#14 0x086d58ce in ?? ()
#15 0x086d90d3 in ?? ()
#16 0x08a65c0b in ?? ()
#17 0x08a66d34 in ?? ()
#18 0x087bb5b2 in ?? ()
#19 0x085debfb in ?? ()
#20 0x082d87b5 in _start ()
```

**Comment by konradmb** [comment]
Fixed.
I've removed debian package and pasted "gdk-pixbuf" module from my yaml.
Before I submit a PR, are you OK with compiling from source? I remember flathub had a policy of requiring only source-build modules, but I see they've changed it?

**Comment by hmenke** [comment]
@konradmb I would very much like to have dependencies built from source, cf. #2. Looking forward to your PR!

**Comment by konradmb** [comment]
I don't know how I haven't seen #2
